- hosts: jenkins 

  vars:
    jenkins_version: "2.89.2"
    jenkins_url: "http://{{ inventory_hostname }}"
    jenkins_port: 8080
    jenkins_install_via: "apt"
    jenkins_jobs: "{{ jenkins_jobs }}" 
    jenkins_plugins:
      - build-pipeline-plugin
    jenkins_custom_files: 
      - src: "jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml"
        dest: "jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml"

  roles: 
   - emmetog.jenkins
