- hosts: 127.0.0.1

  vars:
    jenkins_version: "2.89.2"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "docker"
    jenkins_jobs: [
        "mage-server",
      ]

  roles: 
   - emmetog.jenkins
